apiVersion: v1
kind: Service
metadata:
  name: rag-demo
spec:
  selector:
    app: rag-demo
  ports:
    - protocol: "TCP"
      port: 8502
      targetPort: 8502
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-demo
spec:
  selector:
    matchLabels:
      app: rag-demo
  replicas: 5
  template:
    metadata:
      labels:
        app: rag-demo
    spec:
      containers:
        - name: rag-demo
          image: docker.io/rudrakshkarpe/
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8502